version: '3.9'
services:
  nats:
    image: docker.io/nats:2.9.11
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--debug"
      - "--http_port=8222"
      - "--js"

  debezium:
    image: docker.io/debezium/server:2.1.1.Final
    volumes:
      - ./application.properties:/debezium/conf/application.properties
    depends_on:
      - nats
    extra_hosts:
      - "host.docker.internal:host-gateway"