version: '3.9'
services:
  #postgres:
  #  image: docker.io/debezium/postgres:15
  #  ports:
  #    - "5433:5432"
  #  environment:
  #    POSTGRES_PASSWORD: postgres
  #  healthcheck:
  #    test: ["CMD-SHELL", "pg_isready"]
  #    interval: 10s
  #    timeout: 5s
  #    retries: 5
  nats:
    image: docker.io/nats:2.9.11
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--debug"
      - "--http_port=8222"
      - "--js"

  debezium:
    image: docker.io/debezium/server:2.1.1.Final
    volumes:
      - ./application.properties:/debezium/conf/application.properties
    depends_on:
      - nats
      #- postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"