INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('AFGHANISTAN','004','AF','AFG','111-afghanistan.png',true),
	 ('ANGOLA','024','AO','AGO','117-angola.png',true),
	 ('ANTARCTICA','010','AQ','ATA',NULL,true),
	 ('FRENCH GUIANA','254','GF','GUF',NULL,true),
	 ('FRENCH SOUTHERN TERRITORIES','260','TF','ATF',NULL,true),
	 ('GUADELOUPE','312','GP','GLP',NULL,true),
	 ('GUYANA','328','GY','GUY',NULL,true),
	 ('HEARD AND MC DONALD ISLANDS','334','HM','HMD',NULL,true),
	 ('ARUBA','553','AW','ABW','042-aruba.png',true),
	 ('LATVIA','428','LV','LVA','044-latvia.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('ANDORRA','020','AD','AND','045-andorra.png',true),
	 ('DOMINICAN REPUBLIC','214','DO','DOM','047-dominican-republic.png',true),
	 ('CAYMAN ISLANDS','136','KY','CYM','051-cayman-islands.png',true),
	 ('GHANA','288','GH','GHA','053-ghana.png',true),
	 ('GUINEA-BISSAU','624','GW','GNB','056-guinea-bissau.png',true),
	 ('BURUNDI','108','BI','BDI','057-burundi.png',true),
	 ('GABON','266','GA','GAB','059-gabon.png',true),
	 ('BENIN','204','BJ','BEN','060-benin.png',true),
	 ('JAPAN','392','JP','JPN','063-japan.png',true),
	 ('ERITREA','232','ER','ERI','065-eritrea.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('CHAD','148','TD','TCD','066-chad.png',true),
	 ('KENYA','404','KE','KEN','067-kenya.png',true),
	 ('DJIBOUTI','262','DJ','DJI','068-djibouti.png',true),
	 ('BRITISH INDIAN OCEAN TERRITORY','086','IO','IOT','069-british-indian-ocean-territory.png',true),
	 ('BERMUDA','060','BM','BMU','081-bermuda.png',true),
	 ('BARBADOS','052','BB','BRB','084-barbados.png',true),
	 ('AALAND ISLANDS','248','AX','ALA','087-aland-islands.png',true),
	 ('BURKINA FASO','854','BF','BFA','090-burkina-faso.png',true),
	 ('KOREA, REPUBLIC OF','410','KR','KOR','094-south-korea.png',true),
	 ('GUATEMALA','320','GT','GTM','098-guatemala.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('ALBANIA','008','AL','ALB','099-albania.png',true),
	 ('ECUADOR','218','EC','ECU','104-ecuador.png',true),
	 ('CAMEROON','120','CM','CMR','105-cameroon.png',true),
	 ('KUWAIT','414','KW','KWT','107-kwait.png',true),
	 ('ARMENIA','051','AM','ARM','108-armenia.png',true),
	 ('GUINEA','324','GN','GIN','110-guinea.png',true),
	 ('GREENLAND','304','GL','GRL','113-greenland.png',true),
	 ('HUNGARY','348','HU','HUN','115-hungary.png',true),
	 ('BRUNEI DARUSSALAM','096','BN','BRN','119-brunei.png',true),
	 ('FAROE ISLANDS','234','FO','FRO','122-faroe-islands.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('HOLY SEE (VATICAN CITY STATE)','336','VA','VAT','124-vatican-city.png',true),
	 ('FINLAND','246','FI','FIN','125-finland.png',true),
	 ('BOTSWANA','072','BW','BWA','126-botswana.png',true),
	 ('CHILE','152','CL','CHL','131-chile.png',true),
	 ('BOSNIA AND HERZEGOVINA','070','BA','BIH','132-bosnia-and-herzegovina.png',true),
	 ('LIECHTENSTEIN','438','LI','LIE','134-liechtenstein.png',true),
	 ('BELARUS','112','BY','BLR','135-belarus.png',true),
	 ('IRAN (ISLAMIC REPUBLIC OF)','364','IR','IRN','136-iran.png',true),
	 ('FIJI','242','FJ','FJI','137-fiji.png',true),
	 ('BAHRAIN','048','BH','BHR','138-bahrain.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('COTE D''IVOIRE','384','CI','CIV','161-ivory-coast.png',true),
	 ('GERMANY','276','DE','DEU','162-germany.png',true),
	 ('CROATIA','191','HR','HRV','164-croatia.png',true),
	 ('BELGIUM','056','BE','BEL','165-belgium.png',true),
	 ('BULGARIA','100','BG','BGR','168-bulgaria.png',true),
	 ('LIBERIA','430','LR','LBR','169-liberia.png',true),
	 ('GREECE','300','GR','GRC','170-greece.png',true),
	 ('DENMARK','208','DK','DNK','174-denmark.png',true),
	 ('LESOTHO','426','LS','LSO','176-lesotho.png',true),
	 ('COLOMBIA','170','CO','COL','177-colombia.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('IRELAND','372','IE','IRL','179-ireland.png',true),
	 ('FRENCH POLYNESIA','258','PF','PYF','180-french-polynesia.png',true),
	 ('HONG KONG','344','HK','HKG','183-hong-kong.png',true),
	 ('HAITI','332','HT','HTI','185-haiti.png',true),
	 ('DOMINICA','212','DM','DMA','186-dominica.png',true),
	 ('EQUATORIAL GUINEA','226','GQ','GNQ','189-equatorial-guinea.png',true),
	 ('FRANCE','250','FR','FRA','195-france.png',true),
	 ('ARGENTINA','032','AR','ARG','198-argentina.png',true),
	 ('GUERNSEY','831','GG','GGY','204-guernsey.png',true),
	 ('GUAM','316','GU','GUM','207-guam.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('INDONESIA','360','ID','IDN','209-indonesia.png',true),
	 ('GRENADA','308','GD','GRD','210-grenada.png',true),
	 ('GIBRALTAR','292','GI','GIB','213-gibraltar.png',true),
	 ('FALKLAND ISLANDS (MALVINAS)','238','FK','FLK','215-falkland-islands.png',true),
	 ('ISLE OF MAN','833','IM','IMN','219-isle-of-man.png',true),
	 ('LIBYA','434','LY','LBY','231-libya.png',true),
	 ('AUSTRALIA','036','AU','AUS','234-australia.png',true),
	 ('CANADA','124','CA','CAN','243-canada.png',true),
	 ('JERSEY','832','JE','JEY','245-jersey.png',true),
	 ('INDIA','356','IN','IND','246-india.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('CONGO, THE DEMOCRATIC REPUBLIC OF THE','180','CD','COD','249-democratic-republic-of-congo.png',true),
	 ('BRAZIL','076','BR','BRA','255-brazil.png',true),
	 ('GEORGIA','268','GE','GEO','256-georgia.png',true),
	 ('KIRIBATI','296','KI','KIR','261-kiribati.png',true),
	 ('BOUVET ISLAND','074','BV','BVT','143-norway.png',true),
	 ('CURAÇAO','531','CW','CUW','116-curacao.png',true),
	 ('LAO PEOPLE''S DEMOCRATIC REPUBLIC','418','LA','LAO','112-laos.png',true),
	 ('SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA','654','SH','SHN',NULL,true),
	 ('SAINT KITTS AND NEVIS','659','KN','SKN',NULL,true),
	 ('SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','239','GS','SGS',NULL,true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('TANZANIA, UNITED REPUBLIC OF','834','TZ','TAN',NULL,true),
	 ('VIETNAM','704','VN','VIE',NULL,true),
	 ('VIRGIN ISLANDS (BRITISH)','092','VG','BVI',NULL,true),
	 ('WESTERN SAHARA','732','EH','ESH',NULL,true),
	 ('MAURITIUS','480','MU','MUS','001-mauritius.png',true),
	 ('CYPRUS','196','CY','CYP','002-cyprus.png',true),
	 ('AUSTRIA','040','AT','AUT','003-austria.png',true),
	 ('OMAN','512','OM','OMN','004-oman.png',true),
	 ('NEPAL','524','NP','NPL','016-nepal.png',true),
	 ('PARAGUAY','600','PY','PRY','041-paraguay.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('MONTSERRAT','500','MS','MSR','043-montserrat.png',true),
	 ('MICRONESIA, FEDERATED STATES OF','583','FM','FSM','046-micronesia.png',true),
	 ('TUNISIA','788','TN','TUN','049-tunisia.png',true),
	 ('MAURITANIA','478','MR','MRT','050-mauritania.png',true),
	 ('MYANMAR','104','MM','MMR','058-myanmar.png',true),
	 ('NAMIBIA','516','NA','NAM','062-namibia.png',true),
	 ('LITHUANIA','440','LT','LTU','064-lithuania.png',true),
	 ('SAINT VINCENT AND THE GRENADINES','670','VC','VCT','241-st-vincent-and-the-grenadines.png',true),
	 ('MAYOTTE','175','YT','MYT','195-france.png',true),
	 ('SOLOMON ISLANDS','090','SB','SLB','085-solomon-islands.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('NIGERIA','566','NG','NGA','086-nigeria.png',true),
	 ('URUGUAY','858','UY','URY','088-uruguay.png',true),
	 ('SINT MAARTEN (DUTCH PART)','534','SX','SXM','089-sint-maarten.png',true),
	 ('SLOVAKIA','703','SK','SVK','091-slovakia.png',true),
	 ('SIERRA LEONE','694','SL','SLE','092-sierra-leone.png',true),
	 ('PITCAIRN','612','PN','PCN','095-pitcairn-islands.png',true),
	 ('NEW ZEALAND','554','NZ','NZL','121-new-zealand.png',true),
	 ('SRI LANKA','144','LK','LKA','127-sri-lanka.png',true),
	 ('SPAIN','724','ES','ESP','128-spain.png',true),
	 ('SAUDI ARABIA','682','SA','SAU','133-saudi-arabia.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('VENEZUELA, BOLIVARIAN REPUBLIC OF','862','VE','VEN','139-venezuela.png',true),
	 ('TIMOR-LESTE','626','TL','TLS','140-east-timor.png',true),
	 ('NORWAY','578','NO','NOR','143-norway.png',true),
	 ('UKRAINE','804','UA','UKR','145-ukraine.png',true),
	 ('UNITED ARAB EMIRATES','784','AE','ARE','151-united-arab-emirates.png',true),
	 ('SWAZILAND','748','SZ','SWZ','154-swaziland.png',true),
	 ('PAPUA NEW GUINEA','598','PG','PNG','163-papua-new-guinea.png',true),
	 ('MOROCCO','504','MA','MAR','166-morocco.png',true),
	 ('MACAO','446','MO','MAC','167-macao.png',true),
	 ('SAINT LUCIA','662','LC','LCA','172-st-lucia.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('MALI','466','ML','MLI','173-mali.png',true),
	 ('PALAU','585','PW','PLW','178-palau.png',true),
	 ('TRINIDAD AND TOBAGO','780','TT','TTO','181-trinidad-and-tobago.png',true),
	 ('NIUE','570','NU','NIU','182-niue.png',true),
	 ('SWEDEN','752','SE','SWE','184-sweden.png',true),
	 ('MARTINIQUE','474','MQ','MTQ','201-martinique.png',true),
	 ('TAIWAN, PROVINCE OF CHINA','158','TW','TWN','202-taiwan.png',true),
	 ('SWITZERLAND','756','CH','CHE','205-switzerland.png',true),
	 ('RWANDA','646','RW','RWA','206-rwanda.png',true),
	 ('PALESTINE, STATE OF','275','PS','PSE','208-palestine.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('POLAND','616','PL','POL','211-poland.png',true),
	 ('MOLDOVA, REPUBLIC OF','498','MD','MDA','212-moldova.png',true),
	 ('MALAWI','454','MW','MWI','214-malawi.png',true),
	 ('VIRGIN ISLANDS (U.S.)','850','VI','VIR','217-virgin-islands.png',true),
	 ('TURKEY','792','TR','TUR','218-turkey.png',true),
	 ('TUVALU','798','TV','TUV','221-tuvalu.png',true),
	 ('NIGER','562','NE','NER','222-niger.png',true),
	 ('TURKS AND CAICOS ISLANDS','796','TC','TCA','223-turks-and-caicos.png',true),
	 ('MADAGASCAR','450','MG','MDG','242-madagascar.png',true),
	 ('SOUTH SUDAN','728','SS','SSD','244-south-sudan.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('SOMALIA','706','SO','SOM','247-somaliland.png',true),
	 ('RUSSIAN FEDERATION','643','RU','RUS','248-russia.png',true),
	 ('SAMOA','882','WS','WSM','251-samoa.png',true),
	 ('MEXICO','484','MX','MEX','252-mexico.png',true),
	 ('SEYCHELLES','690','SC','SYC','253-seychelles.png',true),
	 ('MONGOLIA','496','MN','MNG','258-mongolia.png',true),
	 ('UNITED KINGDOM*','826','GB','GBR','260-united-kingdom.png',true),
	 ('NEW CALEDONIA','540','NC','NCL','195-france.png',true),
	 ('NORTHERN MARIANA ISLANDS','580','MP','MNP','160-northern-marianas-islands.png',true),
	 ('REUNION','638','RE','REU','195-france.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('SAINT BARTHÉLEMY','652','BL','BLM','195-france.png',true),
	 ('SAINT PIERRE AND MIQUELON','666','PM','SPM','195-france.png',true),
	 ('SVALBARD AND JAN MAYEN ISLANDS','744','SJ','SJM','143-norway.png',true),
	 ('UNITED STATES','840','US','USA','000-united-states.png',true),
	 ('UNITED STATES MINOR OUTLYING ISLANDS','581','UM','UMI','000-united-states.png',true),
	 ('WALLIS AND FUTUNA ISLANDS','876','WF','WLF','195-france.png',true),
	 ('QATAR','634','QA','QAT','263-qatar.png',true),
	 ('ETHIOPIA','231','ET','ETH','005-ethiopia.png',true),
	 ('NICARAGUA','558','NI','NIC','007-nicaragua.png',true),
	 ('ESTONIA','233','EE','EST','008-estonia.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('UGANDA','800','UG','UGA','009-uganda.png',true),
	 ('SLOVENIA','705','SI','SVN','010-slovenia.png',true),
	 ('ZIMBABWE','716','ZW','ZWE','011-zimbabwe.png',true),
	 ('SAO TOME AND PRINCIPE','678','ST','STP','012-sao-tome-and-prince.png',true),
	 ('ITALY','380','IT','ITA','013-italy.png',true),
	 ('EL SALVADOR','222','SV','SLV','015-el-salvador.png',true),
	 ('CHRISTMAS ISLAND','162','CX','CXR','017-christmas-island.png',true),
	 ('LEBANON','422','LB','LBN','018-lebanon.png',true),
	 ('IRAQ','368','IQ','IRQ','020-iraq.png',true),
	 ('COOK ISLANDS','184','CK','COK','021-cook-islands.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('SYRIAN ARAB REPUBLIC','760','SY','SYR','022-syria.png',true),
	 ('COCOS (KEELING) ISLANDS','166','CC','CCK','023-cocos-island.png',true),
	 ('HONDURAS','340','HN','HND','024-honduras.png',true),
	 ('AMERICAN SAMOA','016','AS','ASM','027-american-samoa.png',true),
	 ('PUERTO RICO','630','PR','PRI','028-puerto-rico.png',true),
	 ('COMOROS','174','KM','COM','029-comoros.png',true),
	 ('KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','408','KP','PRK','030-north-korea.png',true),
	 ('ZAMBIA','894','ZM','ZMB','032-zambia.png',true),
	 ('CHINA','156','CN','CHN','034-china.png',true),
	 ('LUXEMBOURG','442','LU','LUX','035-luxembourg.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('CENTRAL AFRICAN REPUBLIC','140','CF','CAF','036-central-african-republic.png',true),
	 ('JAMAICA','388','JM','JAM','037-jamaica.png',true),
	 ('CAPE VERDE','132','CV','CPV','038-cape-verde.png',true),
	 ('MONACO','492','MC','MCO','039-monaco.png',true),
	 ('BHUTAN','064','BT','BTN','040-bhutan.png',true),
	 ('SERBIA','688','RS','SRB','071-serbia.png',true),
	 ('TOGO','768','TG','TGO','073-togo.png',true),
	 ('KAZAKHSTAN','398','KZ','KAZ','074-kazakhstan.png',true),
	 ('ANTIGUA AND BARBUDA','028','AG','ATG','075-antigua-and-barbuda.png',true),
	 ('SURINAME','740','SR','SUR','076-suriname.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('JORDAN','400','JO','JOR','077-jordan.png',true),
	 ('BELIZE','084','BZ','BLZ','078-belize.png',true),
	 ('ICELAND','352','IS','ISL','080-iceland.png',true),
	 ('MOZAMBIQUE','508','MZ','MOZ','096-mozambique.png',true),
	 ('SAN MARINO','674','SM','SMR','097-san-marino.png',true),
	 ('PAKISTAN','586','PK','PAK','100-pakistan.png',true),
	 ('MARSHALL ISLANDS','485','MH','MHL','103-marshall-island.png',true),
	 ('PANAMA','591','PA','PAN','106-panama.png',true),
	 ('ROMANIA','642','RO','ROU','109-romania.png',true),
	 ('MALAYSIA','458','MY','MYS','118-malasya.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('BAHAMAS','044','BS','BHS','120-bahamas.png',true),
	 ('AZERBAIJAN','031','AZ','AZE','142-tibet.png',true),
	 ('GAMBIA','270','GM','GMB','146-gambia.png',true),
	 ('BANGLADESH','050','BD','BGD','147-bangladesh.png',true),
	 ('CZECH REPUBLIC','203','CZ','CZE','149-czech-republic.png',true),
	 ('BOLIVIA, PLURINATIONAL STATE OF','068','BO','BOL','150-bolivia.png',true),
	 ('KYRGYZSTAN','417','KG','KGZ','152-kyrgyzstan.png',true),
	 ('CUBA','192','CU','CUB','153-cuba.png',true),
	 ('ISRAEL','376','IL','ISR','155-israel.png',true),
	 ('COSTA RICA','188','CR','CRI','156-costa-rica.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('CONGO','178','CG','COG','157-republic-of-the-congo.png',true),
	 ('EGYPT','818','EG','EGY','158-egypt.png',true),
	 ('CAMBODIA','116','KH','KHM','159-cambodia.png',true),
	 ('VANUATU','548','VU','VUT','187-vanuatu.png',true),
	 ('PERU','604','PE','PER','188-peru.png',true),
	 ('UZBEKISTAN','860','UZ','UZB','190-uzbekistn.png',true),
	 ('TONGA','776','TO','TON','191-tonga.png',true),
	 ('PHILIPPINES','608','PH','PHL','192-philippines.png',true),
	 ('NORFOLK ISLAND','574','NF','NFK','193-norfolk-island.png',true),
	 ('MALTA','470','MT','MLT','194-malta.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('TAJIKISTAN','762','TJ','TJK','196-tajikistan.png',true),
	 ('SUDAN','729','SD','SDN','199-sudan.png',true),
	 ('SOUTH AFRICA','710','ZA','ZAF','200-south-africa.png',true),
	 ('PORTUGAL','620','PT','PRT','224-portugal.png',true),
	 ('MALDIVES','462','MV','MDV','225-maldives.png',true),
	 ('SENEGAL','686','SN','SEN','227-senegal.png',true),
	 ('NAURU','520','NR','NRU','228-nauru.png',true),
	 ('TURKMENISTAN','795','TM','TKM','229-turkmenistan.png',true),
	 ('SINGAPORE','702','SG','SGP','230-singapore.png',true),
	 ('YEMEN','887','YE','YEM','232-yemen.png',true);
INSERT INTO geodata.country ("name",code,code_a_2,code_a_3,flag,active) VALUES
	 ('TOKELAU','772','TK','TKL','235-tokelau.png',true),
	 ('MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','807','MK','MKD','236-republic-of-macedonia.png',true),
	 ('NETHERLANDS','528','NL','NLD','237-netherlands.png',true),
	 ('THAILAND','764','TH','THA','238-thailand.png',true),
	 ('MONTENEGRO','499','ME','MNE','239-montenegro.png',true),
	 ('BONAIRE, SINT EUSTATIUS AND SABA','535','BQ','BES','250-sint-eustatius.png',true),
	 ('ALGERIA','012','DZ','DZA','144-algeria.png',true),
	 ('ANGUILLA','660','AI','AIA','025-anguilla.png',true);
